### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "john@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### get submission by id
GET http://localhost:8080/api/v1/submissions/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get submission results by submission id
GET http://localhost:8080/api/v1/submissions/1/results
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}