### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "john@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "mary@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### execute task by Rafał Nowak
POST http://localhost:8080/api/v1/tasks/123/process
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "workspaceUrl": "/Users/rafalnowak/Dev/training/task1"
}

### execute task by Hubert
POST http://localhost:8080/api/v1/tasks/123/subtasks/task_1/fastprocess
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "workspaceUrl": "C:\\Users\\Hubert\\Documents\\Programs\\Python\\MaturaBinaryNumbers"
}

### execute task by Wojtek
POST http://localhost:8080/api/v1/tasks/123/subtasks/task_1/fastprocess
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "workspaceUrl": "G:\\progProjects\\Java\\MaturaBinaryNumbersPython"
}

